# Generated by Django 3.2.6 on 2021-08-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='subcribe_categories',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='category',
            new_name='subcribe_categories',
        ),
    ]
