# Generated by Django 3.2.6 on 2021-08-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscription', '0004_rename_subscribe_categories_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmanager',
            old_name='recipient',
            new_name='subscriber',
        ),
    ]
