# Generated by Django 3.2.6 on 2021-08-04 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscription', '0005_rename_recipient_emailmanager_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmanager',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='emailmanager',
            name='subscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='email_subscription.usersubscription'),
        ),
    ]
