# Generated by Django 3.2.6 on 2021-08-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscription', '0006_auto_20210804_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmanager',
            old_name='message',
            new_name='content',
        ),
    ]
