# Generated by Django 3.2.6 on 2021-08-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscription', '0007_rename_message_emailmanager_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailmanager',
            options={'ordering': ('subject',)},
        ),
        migrations.RemoveField(
            model_name='emailmanager',
            name='sent_date',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='created_date',
        ),
    ]
